insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'T100 Xtra', 'V6', 'gaas', 983, '/ligula/nec/sem/duis/aliquam/convallis/nunc.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Infiniti', 'QX56', 'V12', 'bensiin', 247, '/sagittis/dui/vel/nisl/duis/ac/nibh.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Corvette', 'V6', 'diisel', 297, '/orci/eget/orci/vehicula/condimentum/curabitur/in.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'Century', 'V8', 'diisel', 532, '/pulvinar/lobortis/est.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Volvo', 'XC90', 'V12', 'bensiin', 744, '/potenti/nullam/porttitor/lacus/at/turpis.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Lexus', 'GS', 'V8', 'bensiin', 167, '/venenatis/lacinia/aenean/sit.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'CLK-Class', 'V6', 'diisel', 394, '/nec/molestie/sed/justo/pellentesque/viverra/pede.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Mustang', 'V6', 'bensiin', 542, '/vulputate/justo/in/blandit/ultrices.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Kia', 'Rio5', 'V12', 'diisel', 535, '/nunc/viverra/dapibus.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'Century', 'V6', 'gaas', 921, '/justo.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Citroën', 'SM', 'V6', 'gaas', 440, '/semper/est/quam.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Camaro', 'V6', 'bensiin', 207, '/in/tempor/turpis/nec/euismod.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Cadillac', 'STS-V', 'V6', 'gaas', 270, '/platea/dictumst/etiam/faucibus/cursus.png');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Jimmy', 'V12', 'gaas', 241, '/imperdiet/et/commodo.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Infiniti', 'QX', 'V6', 'gaas', 513, '/eu/sapien/cursus/vestibulum/proin.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'T100', 'V8', 'bensiin', 331, '/sapien/in/sapien.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'MX-5', 'V8', 'bensiin', 742, '/venenatis/tristique/fusce/congue/diam/id.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', '3500 Club Coupe', 'V12', 'elekter', 543, '/ipsum/ac/tellus/semper/interdum.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'RAV4', 'V8', 'gaas', 519, '/vel/est/donec/odio.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Cadillac', 'DeVille', 'V12', 'diisel', 753, '/sit/amet/consectetuer.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Tahoe', 'V8', 'gaas', 153, '/diam/cras.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Acura', 'RL', 'V12', 'elekter', 640, '/sapien/urna/pretium/nisl/ut/volutpat.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Passat', 'V12', 'gaas', 713, '/non/interdum/in/ante.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Volvo', 'V70', 'V12', 'bensiin', 483, '/erat/fermentum/justo/nec/condimentum/neque.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Windstar', 'V6', 'gaas', 681, '/sapien/sapien.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'RX-7', 'V12', 'elekter', 478, '/curabitur/at/ipsum/ac/tellus.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'LeSabre', 'V8', 'gaas', 530, '/tellus/semper/interdum/mauris/ullamcorper/purus.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'E-Series', 'V8', 'bensiin', 535, '/dignissim/vestibulum/vestibulum/ante/ipsum.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'S-Class', 'V8', 'diisel', 381, '/montes/nascetur.png');
insert into cars (mark, model, engine, fuel, price, image) values ('GMC', 'Savana 2500', 'V6', 'elekter', 131, '/duis/faucibus.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Jaguar', 'XJ Series', 'V6', 'bensiin', 562, '/lorem.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Infiniti', 'QX', 'V12', 'gaas', 884, '/justo/aliquam/quis.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Lincoln', 'Mark VIII', 'V8', 'elekter', 774, '/luctus/et/ultrices.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Pontiac', 'LeMans', 'V6', 'elekter', 728, '/orci/eget.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Ford', 'Windstar', 'V8', 'gaas', 431, '/felis/donec.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Aston Martin', 'Vantage', 'V12', 'bensiin', 482, '/iaculis/justo/in.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Suzuki', 'Vitara', 'V8', 'bensiin', 762, '/sed.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Buick', 'Rainier', 'V12', 'elekter', 184, '/sapien/arcu/sed/augue.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Cadillac', 'Eldorado', 'V8', 'gaas', 612, '/vel/enim/sit/amet/nunc.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Prizm', 'V6', 'bensiin', 171, '/mattis.jsp');
